
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SCHOOL
 */
public class viewemp extends javax.swing.JFrame {

    /**
     * Creates new form viewemp
     */
    public viewemp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        empnolabel = new javax.swing.JLabel();
        empnofield = new javax.swing.JTextField();
        lastnamelabel = new javax.swing.JLabel();
        lastnamefield = new javax.swing.JTextField();
        firstnamelabel = new javax.swing.JLabel();
        fistnamefield = new javax.swing.JTextField();
        bdaylabel = new javax.swing.JLabel();
        bdayfield = new javax.swing.JTextField();
        addresslabel = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        pnlabel = new javax.swing.JLabel();
        pnfield = new javax.swing.JTextField();
        ssslabel = new javax.swing.JLabel();
        sssfield = new javax.swing.JTextField();
        phlabel = new javax.swing.JLabel();
        phfield = new javax.swing.JTextField();
        pagibiglabel = new javax.swing.JLabel();
        pagibigfield = new javax.swing.JTextField();
        tinlabel = new javax.swing.JLabel();
        tinfield = new javax.swing.JTextField();
        statuslabel = new javax.swing.JLabel();
        statusfield = new javax.swing.JTextField();
        basiclabel = new javax.swing.JLabel();
        basicfield = new javax.swing.JTextField();
        positionlabel = new javax.swing.JLabel();
        positionfield = new javax.swing.JTextField();
        close2 = new javax.swing.JButton();
        searchemp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(1064, 700));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Profile");

        empnolabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        empnolabel.setForeground(new java.awt.Color(255, 255, 255));
        empnolabel.setText("Employe number:");

        empnofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empnofieldActionPerformed(evt);
            }
        });

        lastnamelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        lastnamelabel.setText("Last Name: ");

        lastnamefield.setEditable(false);
        lastnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnamefieldActionPerformed(evt);
            }
        });

        firstnamelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        firstnamelabel.setText("Fist Name:");

        fistnamefield.setEditable(false);
        fistnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fistnamefieldActionPerformed(evt);
            }
        });

        bdaylabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdaylabel.setForeground(new java.awt.Color(255, 255, 255));
        bdaylabel.setText("Birth date:");

        bdayfield.setEditable(false);
        bdayfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdayfieldActionPerformed(evt);
            }
        });

        addresslabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addresslabel.setForeground(new java.awt.Color(255, 255, 255));
        addresslabel.setText("Address:");

        addressfield.setEditable(false);
        addressfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressfieldActionPerformed(evt);
            }
        });

        pnlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlabel.setForeground(new java.awt.Color(255, 255, 255));
        pnlabel.setText("Phone number: ");

        pnfield.setEditable(false);
        pnfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnfieldActionPerformed(evt);
            }
        });

        ssslabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ssslabel.setForeground(new java.awt.Color(255, 255, 255));
        ssslabel.setText("SSS number:");

        sssfield.setEditable(false);
        sssfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssfieldActionPerformed(evt);
            }
        });

        phlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phlabel.setForeground(new java.awt.Color(255, 255, 255));
        phlabel.setText("PhilHealth number:");

        phfield.setEditable(false);
        phfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phfieldActionPerformed(evt);
            }
        });

        pagibiglabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pagibiglabel.setForeground(new java.awt.Color(255, 255, 255));
        pagibiglabel.setText("PagIBIG number:");

        pagibigfield.setEditable(false);
        pagibigfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagibigfieldActionPerformed(evt);
            }
        });

        tinlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tinlabel.setForeground(new java.awt.Color(255, 255, 255));
        tinlabel.setText("TIN:");

        tinfield.setEditable(false);
        tinfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinfieldActionPerformed(evt);
            }
        });

        statuslabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statuslabel.setForeground(new java.awt.Color(255, 255, 255));
        statuslabel.setText("Status:");

        statusfield.setEditable(false);
        statusfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusfieldActionPerformed(evt);
            }
        });

        basiclabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        basiclabel.setForeground(new java.awt.Color(255, 255, 255));
        basiclabel.setText("Basic Salary:");

        basicfield.setEditable(false);
        basicfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicfieldActionPerformed(evt);
            }
        });

        positionlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        positionlabel.setForeground(new java.awt.Color(255, 255, 255));
        positionlabel.setText("Position:");

        positionfield.setEditable(false);
        positionfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionfieldActionPerformed(evt);
            }
        });

        close2.setText("Close");
        close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close2ActionPerformed(evt);
            }
        });

        searchemp.setText("Search");
        searchemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(317, 317, 317))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empnolabel)
                    .addComponent(lastnamelabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(firstnamelabel)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addresslabel)
                            .addComponent(bdaylabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssslabel)
                            .addComponent(pnlabel)
                            .addComponent(phlabel)
                            .addComponent(pagibiglabel)
                            .addComponent(tinlabel)
                            .addComponent(statuslabel)
                            .addComponent(basiclabel)
                            .addComponent(positionlabel))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(empnofield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(searchemp, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lastnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fistnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdayfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sssfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagibigfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tinfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basicfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(positionfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 567, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empnolabel)
                    .addComponent(empnofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchemp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnamelabel)
                    .addComponent(lastnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnamelabel)
                    .addComponent(fistnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdaylabel)
                    .addComponent(bdayfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addresslabel)
                    .addComponent(addressfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlabel)
                    .addComponent(pnfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssslabel)
                    .addComponent(sssfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phlabel)
                    .addComponent(phfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagibiglabel)
                    .addComponent(pagibigfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tinlabel)
                    .addComponent(tinfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statuslabel)
                    .addComponent(statusfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basiclabel)
                    .addComponent(basicfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionlabel)
                    .addComponent(positionfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(close2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empnofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empnofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empnofieldActionPerformed

    private void lastnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnamefieldActionPerformed

    private void fistnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fistnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fistnamefieldActionPerformed

    private void bdayfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdayfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdayfieldActionPerformed

    private void addressfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressfieldActionPerformed

    private void pnfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnfieldActionPerformed

    private void sssfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sssfieldActionPerformed

    private void phfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phfieldActionPerformed

    private void pagibigfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagibigfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagibigfieldActionPerformed

    private void tinfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinfieldActionPerformed

    private void statusfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusfieldActionPerformed

    private void basicfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basicfieldActionPerformed

    private void positionfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionfieldActionPerformed

    private void close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        homepage pi = new homepage();
        pi.setVisible(true);
    }//GEN-LAST:event_close2ActionPerformed

    private void searchempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchempActionPerformed
       
     
    String empNo = empnofield.getText().trim();
    if (empNo.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter Employee Number to search.");
        return;
    }

    String filePath = "C:\\Users\\SCHOOL\\Documents\\NetBeansProjects\\MotorPH_Employee_Application\\src\\empinfo.csv";
    boolean found = false;
    getResourceAsStream();
   

    try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
        String line;

        while ((line = br.readLine()) != null) {
            String[] data = line.split(",", -1); // Preserve empty strings
            if (data.length >= 13 && data[0].equals(empNo)) {
                lastnamefield.setText(data[1]);
                fistnamefield.setText(data[2]);
                bdayfield.setText(data[3]);
                addressfield.setText(data[4]);
                pnfield.setText(data[5]);
                sssfield.setText(data[6]);
                phfield.setText(data[7]);
                pagibigfield.setText(data[8]);
                tinfield.setText(data[9]);
                statusfield.setText(data[10]);
                basicfield.setText(data[11]);
                positionfield.setText(data[12]);
                found = true;
                break;
            }
        }
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "Error reading empinfo.csv: " + ex.getMessage());
        return;
    }

    if (!found) {
        JOptionPane.showMessageDialog(null, "Employee number " + empNo + " not found.");
    }
  
    }//GEN-LAST:event_searchempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewemp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressfield;
    private javax.swing.JLabel addresslabel;
    private javax.swing.JTextField basicfield;
    private javax.swing.JLabel basiclabel;
    private javax.swing.JTextField bdayfield;
    private javax.swing.JLabel bdaylabel;
    private javax.swing.JButton close2;
    private javax.swing.JTextField empnofield;
    private javax.swing.JLabel empnolabel;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JTextField fistnamefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastnamefield;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JTextField pagibigfield;
    private javax.swing.JLabel pagibiglabel;
    private javax.swing.JTextField phfield;
    private javax.swing.JLabel phlabel;
    private javax.swing.JTextField pnfield;
    private javax.swing.JLabel pnlabel;
    private javax.swing.JTextField positionfield;
    private javax.swing.JLabel positionlabel;
    private javax.swing.JButton searchemp;
    private javax.swing.JTextField sssfield;
    private javax.swing.JLabel ssslabel;
    private javax.swing.JTextField statusfield;
    private javax.swing.JLabel statuslabel;
    private javax.swing.JTextField tinfield;
    private javax.swing.JLabel tinlabel;
    // End of variables declaration//GEN-END:variables

    private void getResourceAsStream() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
